// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqWM9oT15MEWJ08akkOGoE_rfO7hZcPj4',
    appId: '1:134141366024:web:aac5617b3549528bad66bd',
    messagingSenderId: '134141366024',
    projectId: 'malnudetect',
    authDomain: 'malnudetect.firebaseapp.com',
    storageBucket: 'malnudetect.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj4h6HzTwETjtzq7tZgAGcPvcqdlcoaSE',
    appId: '1:134141366024:android:40b370af9dc0a1cdad66bd',
    messagingSenderId: '134141366024',
    projectId: 'malnudetect',
    storageBucket: 'malnudetect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApkCPXisM5sUZxuNshjF8Pe6E3ER7y4fs',
    appId: '1:134141366024:ios:85e6190f678f2cfaad66bd',
    messagingSenderId: '134141366024',
    projectId: 'malnudetect',
    storageBucket: 'malnudetect.appspot.com',
    iosBundleId: 'com.example.malnudetect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApkCPXisM5sUZxuNshjF8Pe6E3ER7y4fs',
    appId: '1:134141366024:ios:48e3715ebe7dd5a8ad66bd',
    messagingSenderId: '134141366024',
    projectId: 'malnudetect',
    storageBucket: 'malnudetect.appspot.com',
    iosBundleId: 'com.example.malnudetect.RunnerTests',
  );
}
